import { appendFileSync, writeFileSync } from 'fs';
import { tryJsonParse } from '../helpers.js';
import { Chat, Model, Provider, Reply } from '../types.js';
import { join } from 'path';

export interface Choice {
  // [stop, length, content_filter, tool_calls, insufficient_system_resources]
  finish_reason: string;
  // index in the choices array
  index: number;
  // chat completion message generated by the llm
  message: {
    // assistant
    role: string;
    // contents of the message
    content: string;
    reasoning_content?: string;
    tool_calls?: {
      id: string;
      // "function"
      type: string;
      // info about the function tool call
      function: {
        // name of the function call
        name: string;
        // JSON, but might not be valid
        arguments: string;
      };
    }[];
  };
}

export default class DeepseekModel extends Model {
  provider: Provider = 'deepseek';
  public baseUrl: string = 'https://api.deepseek.com';

  // moves DSML tools int .tools, cleans the content
  prepChoice(choice: Choice): Choice {
    // DSML tool_calls: <｜DSML｜tool_calls>...</｜DSML｜tool_calls>
    const dsml = /<tool_calls>([\s\S]*?)<\/tool_calls>/g;
    let block: RegExpExecArray | null;
    // inside choice.message.content there might be stray DSML tags: parse them
    while ((block = dsml.exec(choice.message.content)) !== null) {
      const invokes = block[1]!.match(/<invoke name="([^"]+)"[^>]*>([\s\S]*?)<\/invoke>/g) || [];
      for (const invoke of invokes) {
        const name = invoke.match(/<invoke name="([^"]+)"[^>]*>/)?.[1];
        if (!name) continue;

        const params: { [key: string]: string } = {};
        const paramRe = /<parameter name="([^"]+)"[^>]*>([\s\S]*?)<\/parameter>/g;
        let param: RegExpExecArray | null;
        while ((param = paramRe.exec(invoke)) !== null) {
          params[param[1]!] = param[2]!.trim();
        }

        const args = JSON.stringify(params);
        const exists = choice.message.tool_calls?.some(
          (t) => t.function.name === name && t.function.arguments === args
        );
        if (!exists) {
          choice.message.tool_calls = choice.message.tool_calls || [];
          choice.message.tool_calls.push({
            id: `call_${choice.message.tool_calls.length}`,
            type: 'function',
            function: { name, arguments: args },
          });
        }
      }
      choice.message.content = choice.message.content.replace(block[0], '');
    }

    // trim the content, nothing else to do: the LLM returns plain text
    choice.message.content = choice.message.content.trim();

    // returned choice should be clean of DSML tags, with all generated tool_calls
    return choice;
  }

  async execChat(chat: Chat) : Promise<Reply> {
    const chatId = chat.id || 'deepseek-' + Date.now();
    const body: { [key: string]: any } = {};

    body.model = this.model;
    body.messages = chat.messages.map(m => JSON.parse(JSON.stringify({
      role: m.role, 
      content: m.content, 
      name: 'Human', 
      tool_call_id: m.toolId, 
      tool_calls: m.tools?.map(t => ({
        id: t.id,
        type: 'function',
        function: {
          name: t.name,
          arguments: JSON.stringify(t.arguments),
        },
      })),
    })));

    body.stream = false;
    body.thinking = { type: (chat.thinking ? 'enabled' : 'disabled') };

    // user_id has a strict contract ([a-zA-Z0-9_-]{1,512}): only send it when present
    if (chat.userId) {
      body.user_id = chat.userId;
    }

    // reasoning_effort is only supported while thinking mode is enabled
    if (chat.thinking) {
      body.reasoning_effort = this.reasoning; // TODO: this should be configurable depending on the task
    }

    body.tools = chat.tools;
    body.tool_choice = body.tools?.length ? 'auto' : 'none';
    body.temperature = this.temperature;
    body.top_p = this.topP;
    body.max_tokens = this.maxTokens;

    appendFileSync(join(this.engine.work,'logs', `${chatId}.log`), '\n\n--- LLM request ---\n' + JSON.stringify(body, null, 2));

    // TODO: remove this
    this.logger.debug('[DeepseekModel.sendChat]', 'request', `id=${chat.id} userId=${chat.userId}`);

    // call the model api
    const apiKey = this.apiKey || process.env.DEEPSEEK_API_KEY;
    const response = await fetch(`${this.baseUrl}/v1/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify(body),
    });

    // check if response is ok
    if (!response.ok) {
      this.logger.error('[DeepseekModel.sendChat]', 'response NOT ok:', response);
      const body = await response.json();
      throw new Error(`[DeepseekModel.sendChat] ERROR ${body.error?.message || body.message || response.statusText}`);
    }

    // extract json from response
    const json = await response.json();

    // TODO: remove this
    appendFileSync(join(this.engine.work,'logs', `${chatId}.log`), '--- LLM response ---\n' + JSON.stringify(json, null, 2));

    // no choices, no reply
    if (!json.choices || json.choices.length === 0) {
      this.logger.warn('[DeepseekModel.sendChat]', 'no choices, no reply');
      return { id: json.id, stop: true, finish: 'empty', message: { role: 'assistant', content: '' } } as Reply;
    }

    // choice 0, for now only one choice is supported
    const choice = this.prepChoice(json.choices[0] as Choice);
    // llm chat output as a reply object
    const reply = {
      id: json.id, // as string,
      // continue the AI loop only when the model wants to make tool calls;
      // stop/stop on 'length', 'content_filter', etc. too
      stop: choice.finish_reason !== 'tool_calls',
      finish: choice.finish_reason,
      message: {
        role: choice.message.role, // always "assistant" here
        content: choice.message.content,
        tools: choice.message.tool_calls?.map((t: {[key: string]: any}) => ({
          id: t.id,
          name: t.function.name,
          arguments: tryJsonParse(t.function.arguments),
        }))
        // TODO: research of reasoning_content may be needed?
      },
      usage: {
        completion: json.usage?.completion_tokens,
        prompt: json.usage?.prompt_tokens,
      }
    } as Reply;

    this.logger.debug('[DeepseekModel.sendChat]', 'response', `id=${json.id} finish=${choice.finish_reason} tokens=${json.usage?.completion_tokens}`);

    return reply;
  }
}

