import { type Context } from './context.js';

export type Mode = 'client' | 'server';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';
export type Provider = 'fallback' | 'deepseek' | 'lmstudio' | 'openai' | 'qwen' | 'anthropic' | 'google';
export type Thinking = 'enabled' | 'disabled';
export type Role = 'system' | 'user' | 'assistant' | 'tool';

export interface Config {
  timestamp: number;
  settings: {
    name: string;
    port: number;
    logLevel: LogLevel;
  };
  channels: Record<string, {
    enabled: boolean;
    [key: string]: any;
  }>;
  models: Record<string, {
    enabled: boolean;
    provider: Provider;
    model: string;
    baseUrl: string;
    apiKey: string;
  }>;
  agents: Record<string, {
    enabled: boolean;
    default: boolean;
    model: string;
    channels: Record<string, string>;
    tools: string[];
    tasks: Record<string, {
      enabled: boolean;
      schedule: number;
      maxSteps: number;
      input: string;
    }>;
  }>;
}

export abstract class App {
  public context?: Context;

  abstract init(): Promise<void>;
  abstract drop(): Promise<void>;
  
  abstract initContext(): void;
}

export abstract class Tool {
  abstract name(): string;
  abstract info(): string;
  abstract args(): { [name: string]: { type: string; description: string; items?: { type: string }; required: boolean } };
  abstract call(ctx: any, args: any): Promise<any>;
}

// channel interface
export abstract class Channel {
  abstract init(context: Context): Promise<void>;
  abstract drop(): Promise<void>;
  abstract sendMessage(message: Message): Promise<any | null>;
}

// task keeps track of the setTimeout id, schedule
export interface Task {
  id: string;
  enabled: boolean;
  schedule: number;
  maxSteps: number;
  timeout: NodeJS.Timeout | null;
  input: string;
}

// model interface class
export abstract class Model {
  // model is enabled or disabled
  public enabled: boolean = true;
  // model is the default model for the agent
  public default: boolean = false;
  // model provider (e.g. lmstudio, openai, anthropic, deepseek, etc.)
  public provider: Provider = 'lmstudio';
  // model field refers to the LLM identifier.
  public model: string = 'qwen/qwen3.6-35b-a3b';
  // baseUrl is the url to the model provider's API endpoint
  public baseUrl: string = 'http://localhost:1234';
  // apiKey is the API key for the model provider
  public apiKey: string = 'NO_API_KEY';

  public temperature: number = 0.7;
  public topP: number = 0.9;
  public maxTokens: number = 8192;
  public n: number = 1;
  public userId: string = 'user-id';
  public reasoning: string = 'high';
  public format: 'text' | 'json' = 'text';

  constructor(config: { [key: string]: any }) {
    Object.assign(this, config);
  }

  // sends messages to LLM model
  abstract sendChat(chat: Chat): Promise<Reply>;
}

export interface Agent {
  id: string;
  // agent is enabled or disabled
  enabled: boolean;
  // agent system prompt
  identity: string;
  // inside the task, the agent will send messages through these channels to the user/owner
  channels: Record<string, string>;
  // will use this model to communicate with the LLMs
  model: Model;
  // a task is basically a setTimeout that will execute the AI loop then rerun/reschedule itself
  tasks: Record<string, Task>;
}

export interface Chat {
  // used for cache retrieval, restore chat state and continue
  id: string;
  // thinking is enabled or disabled
  thinking: boolean;
  // messages is the chat history
  messages: Message[];
  userId?: string;
  tools?: { 
    type:'function', 
    function: {
      description: string,
      name: string,
      strict: boolean,
      // TODO: verify this again, https://api-docs.deepseek.com/guides/tool_calls
      parameters: {
        type: 'object', // force to object
        required: string[],
        properties: Record<string, {
          type: string,
          description: string,
        }>,
      }
    } 
  }[];
  // sum/total of all usages (Reply.usage)
  usage?: {
    completion: number;
    prompt: number;
  }
}

export interface Message {
  role: Role;
  content: string;
  name?: string;
  channel?: string;
  thread?: string;
  // id of the tool that this message is responding to (role=tool)
  toolId?: string;
  // tool calls generated by the model, use this to execute tools
  tools?: {
    // id of the tool call, useful for .tool_call_id
    id: string;
    // name of the function call
    name: string;
    // arguments as a JSON, might be invalid
    arguments: string; 
  }[];
}

export interface Reply {
  // chat completion id
  id: string;
  // something happened, you need to stop the AI loop
  stop: boolean;
  // finish reason, if stop is true, this is the reason
  finish?: string;
  // message, actual output of the model
  message: Message;
  // usage statistics for this completion request
  usage: {
    completion: number;
    prompt: number;
  };
  // TODO: research if choices?! would be useful
}
